apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: jenkins-monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
      evaluation_interval: 10s

    scrape_configs:
      - job_name: 'jenkins'
        static_configs:
          - targets: ['jolokia-exporter.jenkins-monitoring.svc.cluster.local:8081']
        metrics_path: /metrics
        scheme: http
        basic_auth:
          username: admin
          password: admin
        relabel_configs:
          - source_labels: [__param_target]
            target_label: instance
          - target_label: job
            replacement: jenkins-jolokia

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter.jenkins-monitoring.svc.cluster.local:9100']