apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: jenkins-monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s

    scrape_configs:
      - job_name: 'jenkins'
        static_configs:
          - targets: ['jolokia-exporter.jenkins-monitoring.svc.cluster.local:9442']
        scheme: http
        relabel_configs:
          - source_labels: [__param_target]
            target_label: instance
          - target_label: job
            replacement: jolokia

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter.jenkins-monitoring.svc.cluster.local:9100']