apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: jenkins-monitoring
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30090
  selector:
    app: prometheus