apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins-monitoring
spec:
  selector:
    app: jenkins
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30000