apiVersion: v1
kind: ConfigMap
metadata:
  name: jolokia-exporter-config
  namespace: jenkins-monitoring
data:
  config.yaml: |
    rules:
      - pattern: java.lang<type=Threading><>(.+ThreadCount)
        name: java_lang_threading_$1
        attrNameSnakeCase: true
        type: GAUGE
        help: Java's $1
      - pattern: java.lang<type=Memory><>HeapMemoryUsage/(.+)
        name: java_lang_heap_memory_usage_$1
        attrNameSnakeCase: true
        type: GAUGE
        help: Heap memory $1 usage
      - pattern: java.lang<type=Runtime><>SpecVersion
        name: java_lang_runtime_spec_version
        value: 1
        labels:
          "version": $0
        type: GAUGE